FROM python:3.12.5-bullseye
WORKDIR /app
COPY . .
RUN pip install -r BERT/Required_Modules/requirements.txt 
RUN python -m spacy download en_core_web_lg
WORKDIR /app/BERT/Code_Files
CMD [ "python bert_dashboard.py" ]
