name: CI/CD Workflow for Docker and GKE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - uses: actions/checkout@v4
    
    # Step 2: Set the timestamp variable
    - name: Set timestamp
      id: timestamp
      run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

    # Step 3: Log in to Docker Hub
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Step 4: Build the Docker image
    - name: Build the Docker image
      run: docker build . --file BERT/Code_Files/dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/wex:${{ env.TIMESTAMP }}

    # Step 5: Push the Docker image to Docker Hub
    - name: Push the Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/wex:${{ env.TIMESTAMP }}

    # Step 6: Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    # Step 7: Install gke-gcloud-auth-plugin
    - name: Install gke-gcloud-auth-plugin
      run: gcloud components install gke-gcloud-auth-plugin

    # Step 8: Authenticate with GKE
    - name: Authenticate with GKE
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | base64 -d > $HOME/gcloud-key.json
        gcloud auth activate-service-account --key-file=$HOME/gcloud-key.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud container clusters get-credentials wex-cluster-1 --zone us-central1-c

    # Step 9: Set up kubectl
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    # Step 10: Update the deployment image in the Kubernetes deployment file and apply it
    - name: Deploy to GKE
      run: |
        sed -i "s|image: amanseth91/wex:.*|image: ${{ secrets.DOCKER_USERNAME }}/wex:${{ env.TIMESTAMP }}|g" BERT/Code_Files/k8-deploy.yml
        kubectl apply -f BERT/Code_Files/k8-deploy.yml -n wex

